# Site settings
title: Jake Neiheisel -- Assistant Professor of Political Science
author: Jake Neiheisel
author_title: Assistant Professor of Political Science

email: neiheij@gmail.com
phone: 716-645-8439
address: 422 Park Hall, University at Buffalo, Buffalo, NY
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neiheisel.github.io" # the base hostname & protocol for your site

google_scholar_url: https://scholar.google.com/citations?hl=en&user=aFWS0ooAAAAJ&view_op=list_works&gmla=AJsN-F5S94VkPko9Tk7-p0XcfmYOep5TSYTBBbXxKwgKGh9Ct7hCupj1Bf_1yc-7_QzyWrRyQl51mrdVs7wJeyCR8SLqc0qXFDNC9hCRUGWqwumNuzBmnkkAC7Zkd2ay2ucxfazpvdBdRA4HwpkZ3OWAkEpV12L892EiSOS2i5rBMNWvF6OjxNc
linkedin_url: https://www.linkedin.com/pub/jacob-neiheisel/35/223/20b
github_url: https://www.github.com/neiheisel
cv_url: https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxwb2xpc2NpbmVpaGVpc2VsfGd4OjQ4YjQ2OTZmODA2ZjZmYmY

quotes:
  profile: "\"If angels were to govern men, neither external nor internal controls on government would be necessary.\" -- Federalist # 51"
  education: "\"Religion, morality, and knowledge, being necessary to good government and the happiness of mankind, school and the means of education shall forever be encouraged.\" -- The Ohio Ordinance of 1787, Article III"
  portfolio: "A selection of recent publications and working papers"
  experiences: ""
  teaching: "Recent course syllabi"
  contact: ""

# Build settings
markdown: kramdown
