# Site settings
title: Jake Neiheisel -- Assistant Professor of Political Science
author: Jake Neiheisel
author_title: Assistant Professor of Political Science

email: neiheij@gmail.com
phone: 716-645-8439
address: 422 Park Hall, University at Buffalo, Buffalo, NY
description: >
  I am an Assistant Professor of Political Science at the University at Buffalo, SUNY. I previously
  taught at Denison University. My research interests include: political behavior, election administration,
  parties, religion and politics, and political communication. My work has appeared in such outlets as
  Legislative Studies Quarterly, Political Research Quarterly, American Politics Research, Political
  Communication, Social Science Quarterly, and Polity.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neiheisel.github.io" # the base hostname & protocol for your site

google_scholar_url: https://scholar.google.com/citations?hl=en&user=aFWS0ooAAAAJ&view_op=list_works&gmla=AJsN-F5S94VkPko9Tk7-p0XcfmYOep5TSYTBBbXxKwgKGh9Ct7hCupj1Bf_1yc-7_QzyWrRyQl51mrdVs7wJeyCR8SLqc0qXFDNC9hCRUGWqwumNuzBmnkkAC7Zkd2ay2ucxfazpvdBdRA4HwpkZ3OWAkEpV12L892EiSOS2i5rBMNWvF6OjxNc
linkedin_url: https://www.linkedin.com/pub/jacob-neiheisel/35/223/20b
github_url: https://www.github.com/neiheisel
cv_url: https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxwb2xpc2NpbmVpaGVpc2VsfGd4OjQ4YjQ2OTZmODA2ZjZmYmY

# Build settings
markdown: kramdown

exclude: ["bin"]

collections:
- publications
